# Generated by Django 4.1.7 on 2024-02-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_App', '0005_alter_userdetails_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='User_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
