# Generated by Django 4.1.7 on 2024-02-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Face_App', '0006_attendance_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='User_id',
        ),
    ]
